// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA83557vHbU3Q2DtvzFoglHMsSr571gxNM',
    appId: '1:554147207548:web:87bb28c51ecd497541acf9',
    messagingSenderId: '554147207548',
    projectId: 'duffy-264e6',
    authDomain: 'duffy-264e6.firebaseapp.com',
    storageBucket: 'duffy-264e6.appspot.com',
    measurementId: 'G-4CXLR9ESE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcFPBmbIldVoAJaNJjXsu1OnGpmUHS1Ms',
    appId: '1:554147207548:android:9c0c19013984baeb41acf9',
    messagingSenderId: '554147207548',
    projectId: 'duffy-264e6',
    storageBucket: 'duffy-264e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa6kun7M4PRKg2RBCc7omK_qrAP40xBIQ',
    appId: '1:554147207548:ios:ba2ee8060571d16a41acf9',
    messagingSenderId: '554147207548',
    projectId: 'duffy-264e6',
    storageBucket: 'duffy-264e6.appspot.com',
    iosBundleId: 'com.example.proyectoDdm2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa6kun7M4PRKg2RBCc7omK_qrAP40xBIQ',
    appId: '1:554147207548:ios:13deefec527cfed541acf9',
    messagingSenderId: '554147207548',
    projectId: 'duffy-264e6',
    storageBucket: 'duffy-264e6.appspot.com',
    iosBundleId: 'com.example.proyectoDdm2.RunnerTests',
  );
}
